### ISSUE TITLE
On first open greeted with message "no such table: sqlite_schema"

### ISSUE THREAD

**Issue by jarrod817** [Gip-Gip/pinv#5]
On first open greeted with message "no such table: sqlite_schema". I typed "a" and tried to add category but then it just closes.

**Comment by Gip-Gip** [comment]
> On first open greeted with message "no such table: sqlite_schema". I typed "a" and tried to add category but then it just closes.

Not sure what causes this, but probably a sqlite3 version difference between me and you. I think I have fixed the issue at least in the latest commit.

If this doesn't fix it, please send the output of the command `sqlite3 -version`
